---
- name: Ensure uptime-kuma config folder exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ kuma_host_data_path }}"
    - "{{ kuma_host_config_path }}"

- name: Copy uptime-kuma docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ kuma_host_config_path }}/docker-compose.yml"
    mode: 0644
  become: true

- name: Create systemd uptime-kuma service.
  ansible.builtin.template:
    src: templates/uptime-kuma.service.j2
    dest: "/etc/systemd/system/uptime-kuma.service"
    mode: 0644
  become: true

- name: Ensure uptime-kuma.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: uptime-kuma
  become: true

- name: Check uptime-kuma container
  ansible.builtin.uri:
    url: "http://localhost:{{ kuma_host_port }}"
  register: result
  until: result.status == 200
  retries: 5
  delay: 30

- name: Remove old image versions
  become: true
  docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
