---
- name: Prepare
  hosts: all
  become: true
  vars:
    kuma_container_user: root
    kuma_host_data_path: /etc/uptime-kuma
    pip_install_packages:
      - requests
      - docker
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: create data folder
      ansible.builtin.file:
        dest: "{{kuma_host_data_path}}"
        state: directory
        mode: 0777

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
